version: '3.8'

services:
  worker:
    build: .
    container_name: bike_worker
    restart: always
    # .env 파일에 있는 API KEY들을 컨테이너 안으로 주입
    env_file:
      - .env
    # 코드 수정 시 바로 반영되도록 볼륨 마운트
    volumes:
      - ./scripts:/app/scripts
      - ./data:/app/data